#!/bin/bash

while true; do
    echo ""
    echo "WARNING!!! WARNING!!! WARNING!!! WARNING!!! WARNING!!! WARNING!!!"
    echo "WARNING!!! WARNING!!! WARNING!!! WARNING!!! WARNING!!! WARNING!!!"
    echo "WARNING!!! WARNING!!! WARNING!!! WARNING!!! WARNING!!! WARNING!!!"
    echo "WARNING!!! WARNING!!! WARNING!!! WARNING!!! WARNING!!! WARNING!!!"
    echo "WARNING!!! WARNING!!! WARNING!!! WARNING!!! WARNING!!! WARNING!!!"
    echo "WARNING!!! WARNING!!! WARNING!!! WARNING!!! WARNING!!! WARNING!!!"
    echo "WARNING!!! WARNING!!! WARNING!!! WARNING!!! WARNING!!! WARNING!!!"
    echo ""
    echo "              !!! THIS IS A PHYSICAL SERVER  !!!"
    echo ""
    read -p "      Are you sure you want to shutdown $HOSTNAME? " yn
    echo ""
    case $yn in
        [Yy]* ) make install; break;;
        [Nn]* ) exit;;
        * ) echo "Please answer yes or no.";;
    esac
done
